server:
  port: 4032
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  
